### ISSUE TITLE
Ошибка в документации

### ISSUE THREAD

**Issue by R0mesh** [DirectumCompany/rx-template-appliedhttpclient#2]
в примерах "Применение basic аутентификации" и "Загрузка файла на удаленный сервер" одна переменная **result** объявляется 2 раза:
Сначала явно:
      **var result = string.Empty;**
Потом в лямбде успешного выполнения запроса:
      **.OnSuccess(result =>
       {
         using (StreamReader sr = new StreamReader(result.Response))
         {
           result = sr.ReadToEnd();
         }
       })**

Надо доработать документацию, привести переменные в примерах кода к общему виду, к примеру, с первым вариантом "Отправка метода Get и получение ответа в виде json строки":

**var resultProduct = string.Empty;
......
      .OnSuccess(result =>
       {
         using (StreamReader sr = new StreamReader(result.Response))
         {
           resultProduct = sr.ReadToEnd();
         }**

**Comment by PopovaEI** [comment]
Исправлено
